require "active_support/all"
require "filelist"

require "cleaner/action"
require "cleaner/actions/delete"
require "cleaner/actions/move"
require "cleaner/actions/copy"
require "cleaner/actions/label"
require "cleaner/file_extension"
require "cleaner/directory"
require "cleaner/runner"
require "cleaner/file_filter"
require "cleaner/version"
